"""Template-based agents for demo mode — no API key required."""

from agents.plan_schema import ResearchPlan


def demo_planner(task: str) -> ResearchPlan:
    topic = task.strip().rstrip("?")
    return ResearchPlan(
        objective=f"Research and synthesize current information on: {topic}",
        steps=[
            f"Define scope and key terms related to {topic}",
            "Search authoritative web sources and recent publications",
            "Compare findings across multiple sources",
            "Identify trends, gaps, and actionable insights",
            "Compile a structured research report",
        ],
        expected_sources=[
            "Official documentation and product pages",
            "Technical blogs and industry reports",
            "News articles and community discussions",
        ],
        key_questions=[
            f"What is {topic} and why does it matter?",
            f"What are the latest developments in {topic}?",
            f"Who are the key players or tools in {topic}?",
            f"What challenges or limitations exist around {topic}?",
        ],
    )


def demo_analyst(task: str, plan: ResearchPlan | None, raw_content: str, source_count: int) -> str:
    objective = plan.objective if plan else task
    questions = "\n".join(f"- {q}" for q in (plan.key_questions if plan else []))

    if raw_content.strip():
        preview = raw_content[:2000]
        data_section = f"Based on **{source_count} web sources** collected:\n\n```\n{preview}\n```"
    else:
        data_section = (
            "_No live web sources were retrieved. This demo analysis is based on "
            "general knowledge patterns and the research plan structure._"
        )

    return f"""## Summary
Research objective: {objective}

{data_section}

## Key Trends
- Growing interest and rapid evolution in this topic area
- Multiple frameworks and approaches competing for adoption
- Increasing focus on production-readiness and developer experience
- Integration with existing AI/ML tooling ecosystems

## Critical Insights
- The field is moving quickly — sources from the last 12 months are most relevant
- Open-source tools dominate early adoption; enterprise solutions follow
- Documentation quality varies significantly across sources
- Community consensus is still forming on best practices

## Key Questions Addressed
{questions or "- (No structured plan provided)"}

## Data Gaps & Limitations
- Demo mode uses template analysis — connect OpenAI or Ollama for AI-generated insights
- Web search results depend on DuckDuckGo availability
- Some sources may be outdated or incomplete

## Conclusion
This demo analysis outlines a research framework for **{task}**. For deeper,
source-specific insights, add an `OPENAI_API_KEY` or run [Ollama](https://ollama.com) locally
with `OLLAMA_MODEL=llama3.2` in your `.env` file.
"""


def demo_report(task: str, plan: ResearchPlan | None, analysis: str) -> str:
    objective = plan.objective if plan else task
    return f"""# Research Report: {task}

## Executive Summary
This report presents findings on **{task}**, researched through the Agentic AI
Research Assistant pipeline. {"Live web sources were collected and analyzed." if "web sources" in analysis.lower() else "Analysis was generated in demo mode."}

**Objective:** {objective}

## Key Findings
- The topic spans multiple sub-domains requiring cross-source validation
- Recent developments suggest accelerating adoption and tooling maturity
- Practical implementation requires evaluating trade-offs between approaches
- Semantic memory allows revisiting similar past research sessions

## Insights & Implications
- Researchers and developers should prioritize hands-on evaluation over hype
- Monitoring primary sources (docs, repos, papers) yields the most reliable data
- Multi-agent pipelines improve structure but still need human review

## Recommendations
1. Re-run with an OpenAI API key or local Ollama for AI-powered analysis
2. Narrow the query for more focused source collection
3. Compare results across multiple research sessions using memory
4. Export and refine the markdown report for your portfolio or documentation

## Detailed Analysis
{analysis}

---
*Generated by Agentic AI Research Assistant — Demo Mode*
"""
