from langchain_core.prompts import ChatPromptTemplate

from agents.plan_schema import ResearchPlan
from agents.llm_backend import get_mode, get_llm
from agents.demo_agents import demo_report

PROMPT = ChatPromptTemplate.from_messages([
    ("system", """Generate a professional research report in markdown format.

Structure:
# Research Report: {query}
## Executive Summary
## Key Findings
## Insights & Implications
## Recommendations
## Conclusion
---
*Generated by Agentic AI Research Assistant*"""),
    ("human", "Query: {query}\n\nObjective: {objective}\n\nAnalysis:\n{analysis}")
])


def report_agent(query: str, analysis: str, plan: ResearchPlan | None = None) -> str:
    """Generate a professional structured research report."""
    if get_mode() == "demo":
        return demo_report(query, plan, analysis)

    objective = plan.objective if plan else query
    chain = PROMPT | get_llm()
    return chain.invoke({
        "query": query,
        "objective": objective,
        "analysis": analysis,
    }).content
