from langchain_openai import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
from dotenv import load_dotenv

load_dotenv()

llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.4)

PROMPT = ChatPromptTemplate.from_messages([
    ("system", """Generate a professional research report in markdown format.

Structure:
# Research Report: {query}
## Executive Summary
## Key Findings
## Insights & Implications
## Recommendations
## Conclusion
---
*Generated by Agentic AI Research Assistant*"""),
    ("human", "Query: {query}\n\nAnalysis:\n{analysis}")
])

def report_agent(query: str, analysis: str) -> str:
    """Generate a professional structured research report."""
    chain = PROMPT | llm
    return chain.invoke({"query": query, "analysis": analysis}).content
