[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#ececec"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ececec"
font = "sans serif"
